# Generated by Django 3.1.2 on 2021-10-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=500)),
                ('kode_barang', models.CharField(max_length=500)),
                ('ukuran', models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Renceng', 'Renceng'), ('Bungkus', 'Bungkus')], max_length=500, null=True)),
                ('singkatan', models.CharField(max_length=500)),
                ('katagori', models.CharField(blank=True, choices=[('1', 'Makanan'), ('2', 'Minuman')], max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'db_table': 'barang',
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=500)),
                ('tipe_pembeli', models.CharField(blank=True, choices=[('1', 'Non Member'), ('2', 'Member')], max_length=500, null=True)),
                ('tgl_member', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pembeli',
                'verbose_name_plural': 'Pembeli',
                'db_table': 'pembeli',
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('ukuran', models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Renceng', 'Renceng'), ('Bungkus', 'Bungkus')], max_length=500, null=True)),
                ('stok_barang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stok',
                'db_table': 'stok',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_harus_dibayar', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('nominal_pembayaran', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('nominal_kembalian', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('total_barang', models.CharField(max_length=500)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='barang.pembeli')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_item', models.CharField(max_length=500)),
                ('harga_item', models.CharField(max_length=500)),
                ('diskon_item', models.CharField(max_length=500)),
                ('item_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='barang.barang')),
                ('item_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='barang.order')),
            ],
            options={
                'verbose_name': 'ItemOrder',
                'verbose_name_plural': 'ItemOrder',
                'db_table': 'itemorder',
            },
        ),
    ]
