# Generated by Django 3.1.2 on 2021-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20211025_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
