# Generated by Django 3.1.2 on 2021-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_itemorder_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='satuan',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Renceng', 'Renceng'), ('Bungkus', 'Bungkus')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='ukuran',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
