# Generated by Django 3.1.2 on 2021-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_auto_20211025_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='total_harga_item',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
