# Generated by Django 3.1.2 on 2022-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0009_auto_20220127_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='harga_beli',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
