# Generated by Django 3.1.2 on 2022-01-27 03:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barang', '0010_stok_harga_beli'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='cu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barang',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='mu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorder',
            name='cu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='mu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembeli',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembeli',
            name='cu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembeli',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pembeli',
            name='mu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stok',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stok',
            name='cu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stok',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stok',
            name='mu',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
