# Generated by Django 3.1.2 on 2022-01-31 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barang', '0013_stok_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenjualanBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=500)),
                ('ukuran', models.CharField(max_length=500)),
                ('satuan', models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Renceng', 'Renceng'), ('Bungkus', 'Bungkus')], max_length=500, null=True)),
                ('singkatan', models.CharField(max_length=500)),
                ('katagori', models.CharField(blank=True, choices=[('1', 'Makanan'), ('2', 'Minuman')], max_length=500, null=True)),
                ('harga_barang', models.FloatField(blank=True, null=True)),
                ('harga_jual_langganan', models.FloatField(blank=True, null=True)),
                ('harga_jual', models.FloatField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kobar', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
                ('mu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PenjualanBarang',
                'verbose_name_plural': 'PenjualanBarang',
                'db_table': 'penjualanbarang',
            },
        ),
    ]
