# Generated by Django 3.1.2 on 2022-01-31 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0014_penjualanbarang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualanbarang',
            name='kobar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.barang'),
        ),
    ]
