# Generated by Django 3.1.2 on 2022-01-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0015_auto_20220131_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualanbarang',
            name='isi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
