# Generated by Django 3.1.2 on 2022-01-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0018_auto_20220131_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='item_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='barang.penjualanbarang'),
        ),
    ]
